services:
  todo-app:
    image: minashahir/todo-list-nodejs:latest
    container_name: todo-app
    ports:
      - "80:4000"
    env_file:
      - .env
    restart: always

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3

